### ISSUE TITLE
Minor Bug in resolving full name if suffix matches a salutation

### ISSUE THREAD

**Issue by VinceG** [theiconic/name-parser#11]
The following Name: "PAUL M LEWIS MR"

returns the following

```
Array
(
    [0] => PAUL
    [1] => TheIconic\NameParser\Part\Initial Object
        (
            [value:protected] => M
        )

    [2] => LEWIS
    [3] => TheIconic\NameParser\Part\Salutation Object
        (
            [normalized:protected] => Mr.
            [value:protected] => MR
        )

)
```

making this break and getFirstname and getLastName returns nothing.

the issue seems to be the following line
https://github.com/theiconic/name-parser/blob/master/src/Language/English.php#L41

this probably going to happen with any of the salutations if they come at the end.

Edit:

Another Example:

"SUJAN MASTER"
"JAMES J MA"
"PETER K MA"

**Comment by wyrfel** [comment]
Hi @VinceG . Interesting. Yes, in it's current form the name parser expects the title up-front. The assumption is that if it's in the end, it would be separated by a comma. Do you have actual cases where the title is entered in the end without comma-separation? Theoretically (or rather from the mappers perspective) this should be possible to fix, but in the overall parse order scheme it could complicate things quite a bit as some of the mappers have to make assumptions about positioning.

**Comment by VinceG** [comment]
@wyrfel Thank You for the quick reply and fix.

This seems to fix the issue where the last word matches a salutation in the first case. However this does not seem to fix the other issues

Here are our test cases

```
/** @test */
    public function it_can_parse_saluation_at_end()
    {
        $parsed = (new NameParser)->parse('PAUL M LEWIS MR');
        
        $this->assertEquals('Paul', $parsed->getFirstName());
        $this->assertEquals('Lewis', $parsed->getLastName());
    }

    /** @test */
    public function it_can_parse_saluation_lastname()
    {
        $parsed = (new NameParser)->parse('SUJAN MASTER');

        $this->assertEquals('Sujan', $parsed->getFirstName());
        $this->assertEquals('Master', $parsed->getLastName());
    }

    /** @test */
    public function it_can_parse_saluation_lastname_with_middlename()
    {
        $parsed = (new NameParser)->parse('JAMES J MA');
        
        $this->assertEquals('James', $parsed->getFirstName());
        $this->assertEquals('Ma', $parsed->getLastName());
    }
```

the first one passes the second and third fail. It's worth noting that "PAUL M LEWIS MR" the MR at the end is not the salutation but rather part of his last name the way they write it.

```
1) Tests\Unit\ExampleTest::it_can_parse_saluation_lastname
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Sujan'
+''

/Users/vincentgabriel/Sites/fhalicenses/tests/Unit/ExampleTest.php:33

2) Tests\Unit\ExampleTest::it_can_parse_saluation_lastname_with_middlename
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Ma'
+''
```


```
TheIconic\NameParser\Name Object
(
    [parts:protected] => Array
        (
            [0] => TheIconic\NameParser\Part\Lastname Object
                (
                    [value:protected] => SUJAN
                )

            [1] => TheIconic\NameParser\Part\Salutation Object
                (
                    [normalized:protected] => Mr.
                    [value:protected] => MASTER
                )

        )

)

TheIconic\NameParser\Name Object
(
    [parts:protected] => Array
        (
            [0] => TheIconic\NameParser\Part\Firstname Object
                (
                    [value:protected] => JAMES
                )

            [1] => TheIconic\NameParser\Part\Initial Object
                (
                    [value:protected] => J
                )

            [2] => TheIconic\NameParser\Part\Suffix Object
                (
                    [normalized:protected] => MA
                    [value:protected] => MA
                )

        )

)
```


"SUJAN MASTER"
"JAMES J MA"
"PETER K MA"

The above all fail since the last name is considered a salutation even though it's actually the last name. I am not entirely sure how to properly fix this without having breaking changes. One solution that came to mind is checking the number of parts, if we have 2 parts that is should be considered as first and lastname but then it might cause problems when the name has any other combination of two words such as salutation firstname or middle last name etc..

Thanks again for the help.

**Comment by wyrfel** [comment]
@VinceG All these cases should now be working in version 1.2.6.
I had misunderstood the issue originally, thank you for the clarifications.
I hope this solves the problem more generally for you.
Please see #16 for details.

**Comment by VinceG** [comment]
@wyrfel Thank You. I'll give this a try.
