### ISSUE TITLE
Issue with initials before and after firstname

### ISSUE THREAD

**Issue by jpmschuler** [theiconic/name-parser#21]
I wanted to use this library for cleanup of publication authors and map them to a common format like 
```php
$name->getLastname()).', '.$name->getFirstname() . ' ' . $name->getMiddlename() . ' ' . $name->getInitials())
```
This works flawlessly for barely every name. But as my own second given name is my primary one I often don't spell out my first one, like:
```Schuler, J. Peter M.```
which results in 
```php
Array
(
    [firstname] => Peter
    [initials] => J. M.
    [lastname] => Schuler
)
```
and thus I can't retrieve the correct order of names.

I understand that this is a quite special case, as Germany is one of the few countries were multiple firstnames are possible as well as middle names and where firstnames can be used. Additionally up until a few years ago there was a concept of `primary firstname` which in my case is/was my second one, thus that kind of writing.

Currently I don't understand all of the parsing, but might supply a pull request if I get this to work while still fulfilling the other test cases.

**Comment by wyrfel** [comment]
Hey @jpmschuler . Thanks for reporting this. Off the top of my head i see no issue in pulling initials that precede the firstname into the firstname parts. Although this could lead to Peter being interpreted as middlename, which i'm not sure if that's what you'd want.
The concept of primary name is interesting, too, and could be added as another property.
And finally, i could also imagine adding a position property to the parts that could enable reconstructing the name in the correct order?
I would love to see what you come up with in a pull-request. Let me know if you need any help.

**Comment by jpmschuler** [comment]
That's the same idea I had: Having Peter as middle name who adhere to the current architecture. However that would create an unintended result probably. But that depends on the definition of firstname. If one would use the lib for a greeting in a letter "Hello <firstname>" should resolve to Peter and not to J.

I wondered if it would make sense in general to create a `fullgivenname` property defined as `fullgivenname  = fullname - salutation - lastnameprefix - lastname - suffix`. Which would prevent a keen mapping, but support all languages.

Alternatively I'd try to make a special language definition which drops the distinguishment between firstname, middlename, initials and moves all parts in firstname.

The concept of primary name was dropped from German legislation, thus I don't think it should be implemented (Their replacement is: You can sort your given names anew as an adult if you want to - and that is no joke).

**Comment by jpmschuler** [comment]
After some testing it didn't seem reasonable to change the initial detection. The architecture of the mapping is quite keen and shouldn't be adapted and allows an easy adding of `fullgivenname`. Thus, I think simply adding that new feature will allow broader adoption and will also solve my special case.
