### ISSUE TITLE
Support multi-word salutations (like Air Commodore)

### ISSUE THREAD

**Issue by rvanlaak** [theiconic/name-parser#28]
The current implementation does not support salutations of more than one word.

[Air commodore](https://en.wikipedia.org/wiki/Air_commodore) is an English salutation that consists of more than one word.

What would it take to support more complex salutations?

**Comment by wyrfel** [comment]
Hi @rvanlaak. Interesting request. Tbh, i feel this is a quite uncommon case that i would almost consider out of scope. A lot of military ranks are composed of several words, but i would not necessarily consider them salutations in the sense of common language.

That said, i just had a little ponder about how tricky it would be to implement this and i could imagine that the parser could acquire some sort of rules for splitting the string from the language files. I can't currently fully imagine how that would work, but can imagine it far enough to think it could work, maybe even by accepting a list of strings that should be treated as a single part.

Can you think of more use cases for this than just this one?

**Comment by rvanlaak** [comment]
I locally did get a prototype working that checks the salutations with more than one word if the other ones could not get found.

What I would suggest is to change the `$parts` array into its own value object so more logic can get encapsulated over there.

The parser itself in my opinion should not be responsible of this, the `SalutationMapper` should change the parts if needed.

**Comment by wyrfel** [comment]
:) Just did the same...
https://github.com/theiconic/name-parser/pull/29

**Comment by wyrfel** [comment]
Out of curiosity, what kind of logic would you like to encapsulate in the `$parts` object?
