### ISSUE TITLE
Parsing double last name failed

### ISSUE THREAD

**Issue by rvanlaak** [theiconic/name-parser#30]
For the following book the name gets parsed incorrectly:

https://www.bol.com/nl/p/dans/9200000105098508

Etje Heijdanus-De Boer

## Expected

`Etje` `Heijdanus-De Boer`

## Actual
`Etje Heijdanus-De` `Boer`

**Comment by wyrfel** [comment]
Fixed in #31. Not fully happy with the solution, but should be good enough for now. Again, this points to a need for the part splitting to be smarter.

**Comment by rvanlaak** [comment]
Thank you @wyrfel 👏
