### ISSUE TITLE
Packagist out of sync

### ISSUE THREAD

**Issue by rvanlaak** [theiconic/name-parser#32]
Thank you for the `v1.2.10` release 🎉 

Packagist seems out of sync, `v1.2.8` is the last version available.

Not sure if it has anything to with the Github webhook outage of last week, because the `v.1.2.9` also did not came through.

https://packagist.org/packages/theiconic/name-parser

Can you update / sync the repo?

cc @Seldaek 😉

**Comment by wyrfel** [comment]
The hook needed updating, thanks for pointing it out.
