### ISSUE TITLE
The camelcase conversion does not honor utf-8 characters

### ISSUE THREAD

**Issue by CodeDuck42** [theiconic/name-parser#4]
https://github.com/theiconic/name-parser/blob/faaa310b521cf4407fa360916dab9cced2415476/src/Part/AbstractPart.php#L84

If the mbstring extension is loaded, the following could be used:

~~~php
return mb_convert_case($matches[0], MB_CASE_TITLE, "UTF-8");
~~~

It should be mentioned in the documenation that the program expects to work with utf-8 strings.

Test case:

- input: etna übel
- expected: Etna Übel
- actually: Etna üBel

**Comment by wyrfel** [comment]
Hey Andreas, thanks for the great suggestion. Would you mind opening a PR with the test case added to `ParserTest` and the change in `AbstractPart`?

**Comment by CodeDuck42** [comment]
I created a pull request for the change #5
