### ISSUE TITLE
Fails to parse name with lastname first and middlename last

### ISSUE THREAD

**Issue by francislavoie** [theiconic/name-parser#7]
The test case:

```php
            [
                'Smith, John Eric',
                [
                    'lastname' => 'Smith',
                    'firstname' => 'John',
                    'middlename' => 'Eric',
                ]
            ]
```

It doesn't parse `Eric` as a part, it gets skipped.

I tried making a fix, but gave up after a bit. First, I noticed that the counts of parts in `MiddlenameMapper` is 2, i.e. `["John", "Eric"]` so the first condition there makes it quit out.

I changed that to check to `< 2` to get further. Next, it fails in the `mapFrom` loop because `$k = $start; $k < $length - 1; $k++` becomes `$k = 0; 0 < 1` so it only does one iteration and misses the `Eric` part.

Trying to make that loop not miss the last part, but obviously that will make it fail for every other test case, so I gave up there.

Any idea how this case could be supported? My initial thought is the fact that Lastname was already parsed should be passed in to MiddlenameMapper, so it knows to not skip the last part, but I'm not sure how that information should be passed down the line.

**Comment by wyrfel** [comment]
Nice spotting, thank you for reporting. We solve the same or similar problems in LastnameMapper and SuffixMapper by passing additional constructor options that slightly modify their behaviour. See e.g. [here](https://github.com/theiconic/name-parser/blob/9fa3554942a7358ceb57156da151a8789cfc1a76/src/Parser.php#L104).

We could pass a `$mapWithoutLastname` option to the constructor [here](https://github.com/theiconic/name-parser/blob/9fa3554942a7358ceb57156da151a8789cfc1a76/src/Parser.php#L125) that lowers the count check to a minimum of `2` and changes the loop condition to `$k < $length` (without the `- 1`).

Would you like to try implementing this approach?

**Comment by francislavoie** [comment]
Sure, I can give it a shot tomorrow. Thanks!
